package entity;
// Generated 07/02/2021 17:55:25 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name="movimiento")
public class Movimiento  implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name="idMovimiento")
     private Integer idMovimiento;
    @Column(name="idPartida")
     private Partida partida;
    @Column(name="columna")
     private int columna;
    @Column(name="fila")
     private int fila;

    public Movimiento() {
    }

    public Movimiento(Partida partida, int columna, int fila) {
       this.partida = partida;
       this.columna = columna;
       this.fila = fila;
    }
   
    public Integer getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Integer idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getColumna() {
        return this.columna;
    }
    
    public void setColumna(int columna) {
        this.columna = columna;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }




}


