/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenian;

/**
 *
 * @author Marc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but1vs1 = new javax.swing.JButton();
        but1vsMaquina = new javax.swing.JButton();
        butCarregarPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        but1vs1.setText("1 VS 1");
        but1vs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1vs1ActionPerformed(evt);
            }
        });

        but1vsMaquina.setText("1 VS MAQUINA");
        but1vsMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1vsMaquinaActionPerformed(evt);
            }
        });

        butCarregarPartida.setText("CARREGAR QUALSEVOL PARTIDA");
        butCarregarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCarregarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but1vs1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but1vsMaquina))
                    .addComponent(butCarregarPartida))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but1vs1)
                    .addComponent(but1vsMaquina))
                .addGap(18, 18, 18)
                .addComponent(butCarregarPartida)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but1vs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1vs1ActionPerformed
        // TODO add your handling code here:
        UnoVsUno fra = new UnoVsUno();
        fra.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_but1vs1ActionPerformed

    private void but1vsMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1vsMaquinaActionPerformed
        // TODO add your handling code here:
        UnoVsMaquina fra = new UnoVsMaquina();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_but1vsMaquinaActionPerformed

    private void butCarregarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCarregarPartidaActionPerformed
        // TODO add your handling code here:
        CarregarPartida fra = new CarregarPartida();
        fra.setVisible(true);
        dispose();  
    }//GEN-LAST:event_butCarregarPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1vs1;
    private javax.swing.JButton but1vsMaquina;
    private javax.swing.JButton butCarregarPartida;
    // End of variables declaration//GEN-END:variables
}
