/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenian;

import entity.Movimiento;
import entity.Partida;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author Marc
 */
public class UnoVsUno extends javax.swing.JFrame {

    boolean jugaX = true;
    boolean jugaO = false;
    int contador = 0;
    static Session session;
    static Partida partida;
    static Movimiento movimiento;
    
    
    /**
     * Creates new form unoVSuno
     */
    public UnoVsUno() {
        initComponents();
        table1vs1.setGridColor(Color.black);
        table1vs1.setShowGrid(true);
        table1vs1.setDefaultEditor(Object.class, null);
        partida = new Partida("");
        crearPartida("?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butTornar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1vs1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butTornar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        butTornar.setText("TORNAR");
        butTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTornarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1 VS 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        table1vs1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        table1vs1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table1vs1.setGridColor(new java.awt.Color(0, 0, 0));
        table1vs1.setRowHeight(100);
        table1vs1.setRowSelectionAllowed(false);
        table1vs1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table1vs1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        table1vs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1vs1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1vs1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butTornar)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butTornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTornarActionPerformed
        // TODO add your handling code here:
        Home fra = new Home();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_butTornarActionPerformed

    private void table1vs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1vs1MouseClicked
        // TODO add your handling code here:
        
        int fila = ObtenirFilaClicada();
        int columna = ObtenirColumnaClicada();
        
        if (NoEstaComplert()){
            if(jugaX && EsNull(fila, columna)==true){
                Omple(fila, columna);
                ComprobaGuanyador();
            }else if (jugaO && EsNull(fila,columna)){
                Omple(fila, columna);
                ComprobaGuanyador();
            }else{
                MostraError();
            }
            if(!NoEstaComplert()){
                MostrarEmpat();
                
                Home fra = new Home();
                fra.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_table1vs1MouseClicked

    public boolean NoEstaComplert(){
        
        boolean NoEstaComplert = true;
        if(contador==9){
            NoEstaComplert = false;
        }

       return NoEstaComplert; 
    }
    
    public int ObtenirFilaClicada(){
        return table1vs1.getSelectedRow();
    }
    
    public int ObtenirColumnaClicada(){
        return table1vs1.getSelectedColumn();
    }
    
    public boolean EsNull(int fila, int columna){
        boolean esNull = false;
        if(table1vs1.getValueAt(fila, columna) == null){
            esNull = true;
        }
        return esNull;
    }
    
    public void Omple(int fila, int columna){

        crearMovimiento(columna, fila);
        
        if(jugaX){
            table1vs1.setValueAt("X", fila, columna);
            jugaX = false;
            jugaO = true;
        }else if (jugaO){
            table1vs1.setValueAt("O", fila, columna);
            jugaO = false;
            jugaX = true;
        }
        contador++;
        
    }
    
    public void MostraError(){
        JOptionPane.showMessageDialog(null, "ERROR, NO ESTA BUIT", "ERROR", 
                JOptionPane.ERROR_MESSAGE);
    }
    
    public void MostrarEmpat(){
        JOptionPane.showMessageDialog(null, "EMPAT, NO GUANYA NINGÚ", "EMPAT", 
                JOptionPane.ERROR_MESSAGE);
    }
    
    public void ComprobaGuanyador(){
        
        if((table1vs1.getValueAt(0, 0))=="O" && (table1vs1.getValueAt(0, 1))=="O" && (table1vs1.getValueAt(0, 2))=="O" ||
                (table1vs1.getValueAt(1, 0))=="O" && (table1vs1.getValueAt(1, 1))=="O" && (table1vs1.getValueAt(1, 2))=="O" ||
                (table1vs1.getValueAt(2, 0))=="O" && (table1vs1.getValueAt(2, 1))=="O" && (table1vs1.getValueAt(2, 2))=="O" ||
                (table1vs1.getValueAt(0, 0))=="O" && (table1vs1.getValueAt(1, 0))=="O" && (table1vs1.getValueAt(2, 0))=="O" ||
                (table1vs1.getValueAt(0, 1))=="O" && (table1vs1.getValueAt(1, 1))=="O" && (table1vs1.getValueAt(2, 1))=="O" ||
                (table1vs1.getValueAt(0, 2))=="O" && (table1vs1.getValueAt(1, 2))=="O" && (table1vs1.getValueAt(2, 2))=="O" ||
                (table1vs1.getValueAt(0, 0))=="O" && (table1vs1.getValueAt(1, 1))=="O" && (table1vs1.getValueAt(2, 2))=="O" ||
                (table1vs1.getValueAt(2, 0))=="O" && (table1vs1.getValueAt(1, 1))=="O" && (table1vs1.getValueAt(0, 2))=="O"){
            
                    JOptionPane.showMessageDialog(null, "Jugador 'O' guanya la partida", "GUANYADOR", JOptionPane.OK_OPTION); 
                    Home fra = new Home();
                    fra.setVisible(true);
                    dispose();
                    crearPartida("O");
                    
        } else if((table1vs1.getValueAt(0, 0))=="X" && (table1vs1.getValueAt(0, 1))=="X" && (table1vs1.getValueAt(0, 2))=="X" ||
                (table1vs1.getValueAt(1, 0))=="X" && (table1vs1.getValueAt(1, 1))=="X" && (table1vs1.getValueAt(1, 2))=="X" ||
                (table1vs1.getValueAt(2, 0))=="X" && (table1vs1.getValueAt(2, 1))=="X" && (table1vs1.getValueAt(2, 2))=="X" ||
                (table1vs1.getValueAt(0, 0))=="X" && (table1vs1.getValueAt(1, 0))=="X" && (table1vs1.getValueAt(2, 0))=="X" ||
                (table1vs1.getValueAt(0, 1))=="X" && (table1vs1.getValueAt(1, 1))=="X" && (table1vs1.getValueAt(2, 1))=="X" ||
                (table1vs1.getValueAt(0, 2))=="X" && (table1vs1.getValueAt(1, 2))=="X" && (table1vs1.getValueAt(2, 2))=="X" ||
                (table1vs1.getValueAt(0, 0))=="X" && (table1vs1.getValueAt(1, 1))=="X" && (table1vs1.getValueAt(2, 2))=="X" ||
                (table1vs1.getValueAt(2, 0))=="X" && (table1vs1.getValueAt(1, 1))=="X" && (table1vs1.getValueAt(0, 2))=="X"){
                
                    JOptionPane.showMessageDialog(null, "Jugador 'X' guanya la partida", "GUANYADOR", JOptionPane.OK_OPTION);
                    Home fra = new Home();
                    fra.setVisible(true);
                    dispose();
                    crearPartida("X");
        }
        
    }
    
    public static void crearPartida(String ganador){
        partida.setGanador(ganador);
        
        try {
            session = NewHibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.saveOrUpdate(partida);
            session.getTransaction().commit();
        
        } catch (HibernateException e) {
            System.out.println(" a " + e);
        } finally {
            session.close();
        }
        
    }
    
    public static void crearMovimiento(int columna, int fila) {
        
        movimiento = new Movimiento(partida, columna, fila);
    
        
        movimiento.setPartida(partida);
        movimiento.setColumna(columna);
        movimiento.setFila(fila);

        
        try {
            session = NewHibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            session.persist(movimiento);
            session.getTransaction().commit();
            
        } catch (HibernateException e) {
            System.out.println(" hola marc " + e);
        } finally {
            session.close();
        }
        
    }
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnoVsUno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butTornar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1vs1;
    // End of variables declaration//GEN-END:variables
}
